In [2]:
       # To consume Twitter's API
import tweepy           # To consume Twitter's API
import pandas as pd     # To handle data
import numpy as np      # For number computing

# For plotting and visualization:
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
from pathlib import Path
import os
path = Path.home() / 'result.csv'
cols = ['id', 'timestamp', 'text','link','is_retweet','retweet','favorite','replies']

if os.path.exists(path):
           trump = pd.read_csv(path)
else:
           print(path)

In [4]:
trump.head()

,id,timestamp,text,link,is_retweet,retweets,favorites,replies
0,682319510251159553,1:57 PM - 30 Dec 2015,A lovely letter from the daughter of the late ...,https://twitter.com/realDonaldTrump/status/682...,False,2.7K,6.4K,936
1,682310784563720193,1:22 PM - 30 Dec 2015,Great poll- thank you Nevada!\n#MakeAmericaGre...,https://twitter.com/realDonaldTrump/status/682...,False,1.6K,4.0K,295
2,682297346240167936,12:28 PM - 30 Dec 2015,I'm going to be live with @ericbolling and @ki...,https://twitter.com/realDonaldTrump/status/682...,False,1.9K,4.8K,692
3,682291228898115585,12:04 PM - 30 Dec 2015,"Thank you Hilton Head, South Carolina! #MakeAm...",https://twitter.com/realDonaldTrump/status/682...,False,1.4K,4.0K,315
4,682267088271110145,10:28 AM - 30 Dec 2015,"Thank you Hilton Head, South Carolina! @SCTeam...",https://twitter.com/realDonaldTrump/status/682...,False,1.1K,3.4K,231

In [5]:
trump.shape

(7700, 8)

In [6]:
trump.dtypes

id             int64
timestamp     object
text          object
link          object
is_retweet      bool
retweets      object
favorites     object
replies       object
dtype: object

In [7]:
trump.isnull().sum()

id             0
timestamp      0
text           0
link           0
is_retweet     0
retweets       0
favorites      0
replies       38
dtype: int64

In [8]:
trump.describe()

                 id
count  7.700000e+03
mean   6.122264e+17
std    3.991135e+16
min    5.504414e+17
25%    5.802253e+17
50%    6.108132e+17
75%    6.505248e+17
max    6.823195e+17

In [9]:
trump.loc[:,'hour'] = trump.loc[:,'timestamp'].astype(str).str.slice(0,8)
trump.head()

,id,timestamp,text,link,is_retweet,retweets,favorites,replies,hour
0,682319510251159553,1:57 PM - 30 Dec 2015,A lovely letter from the daughter of the late ...,https://twitter.com/realDonaldTrump/status/682...,False,2.7K,6.4K,936,1:57 PM
1,682310784563720193,1:22 PM - 30 Dec 2015,Great poll- thank you Nevada!\n#MakeAmericaGre...,https://twitter.com/realDonaldTrump/status/682...,False,1.6K,4.0K,295,1:22 PM
2,682297346240167936,12:28 PM - 30 Dec 2015,I'm going to be live with @ericbolling and @ki...,https://twitter.com/realDonaldTrump/status/682...,False,1.9K,4.8K,692,12:28 PM
3,682291228898115585,12:04 PM - 30 Dec 2015,"Thank you Hilton Head, South Carolina! #MakeAm...",https://twitter.com/realDonaldTrump/status/682...,False,1.4K,4.0K,315,12:04 PM
4,682267088271110145,10:28 AM - 30 Dec 2015,"Thank you Hilton Head, South Carolina! @SCTeam...",https://twitter.com/realDonaldTrump/status/682...,False,1.1K,3.4K,231,10:28 AM

In [10]:
trump.loc[:,'date'] = trump.loc[:,'timestamp'].astype(str).str.slice(10,22)
trump.head()

,id,timestamp,text,link,is_retweet,retweets,favorites,replies,hour,date
0,682319510251159553,1:57 PM - 30 Dec 2015,A lovely letter from the daughter of the late ...,https://twitter.com/realDonaldTrump/status/682...,False,2.7K,6.4K,936,1:57 PM,30 Dec 2015
1,682310784563720193,1:22 PM - 30 Dec 2015,Great poll- thank you Nevada!\n#MakeAmericaGre...,https://twitter.com/realDonaldTrump/status/682...,False,1.6K,4.0K,295,1:22 PM,30 Dec 2015
2,682297346240167936,12:28 PM - 30 Dec 2015,I'm going to be live with @ericbolling and @ki...,https://twitter.com/realDonaldTrump/status/682...,False,1.9K,4.8K,692,12:28 PM,30 Dec 2015
3,682291228898115585,12:04 PM - 30 Dec 2015,"Thank you Hilton Head, South Carolina! #MakeAm...",https://twitter.com/realDonaldTrump/status/682...,False,1.4K,4.0K,315,12:04 PM,30 Dec 2015
4,682267088271110145,10:28 AM - 30 Dec 2015,"Thank you Hilton Head, South Carolina! @SCTeam...",https://twitter.com/realDonaldTrump/status/682...,False,1.1K,3.4K,231,10:28 AM,30 Dec 2015

In [14]:
trump.retweets.str.contains("K")

0        True
1        True
2        True
3        True
4        True
5       False
6       False
7       False
8        True
9       False
10       True
11      False
12       True
13       True
14      False
15       True
16       True
17       True
18      False
19       True
20       True
21       True
22       True
23       True
24       True
25       True
26      False
27      False
28      False
29       True
        ...
7670    False
7671    False
7672    False
7673     True
7674    False
7675    False
7676    False
7677    False
7678    False
7679    False
7680    False
7681    False
7682    False
7683    False
7684    False
7685    False
7686    False
7687    False
7688    False
7689    False
7690    False
7691    False
7692    False
7693    False
7694    False
7695    False
7696    False
7697    False
7698    False
7699    False
Name: retweets, Length: 7700, dtype: bool

i want to convert the string into int with k by multiplying it with 1000.

In [12]:
trump.nunique()

id            7700
timestamp     6848
text          7671
link          7700
is_retweet       1
retweets      1015
favorites      906
replies        853
hour          1367
date           626
dtype: int64